// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbvbaaptrnyagffcrcrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidmJhYXB0cm55YWdmZmNyY3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzc4OTAsImV4cCI6MjA3Mzc1Mzg5MH0.XE9u0685NN_gKHdVIgdnAJgmHZt6pXnu9Bj6pubi0Ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});